<a href="https://colab.research.google.com/github/jimmyjims88/computermath/blob/%EC%BD%94%EB%94%A9%EC%8B%A4%EC%8A%B5/3%EC%A3%BC%EC%B0%A8%20%EC%B4%88%EB%93%B1%EB%85%BC%EB%A6%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%83%80%EC%9E%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch                    #논리곱(AND) 코딩

In [ ]:
x = torch.tensor([True, True, False, False])
y = torch.tensor([True, False, True, False])

print(torch.logical_and(x, y))

tensor([ True, False, False, False])


In [2]:
import torch    #논리합(OR) 코딩

In [3]:
x = torch.tensor([True, True, False, False])
y = torch.tensor([True, False, True, False])

print(torch.logical_or(x, y))

tensor([ True,  True,  True, False])


In [4]:
import torch    # 배타적 논리합(XOR) 코딩

In [5]:
x = torch.tensor([True, True, False, False])
y = torch.tensor([True, False, True, False])

print(torch.logical_xor(x, y))

tensor([False,  True,  True, False])


In [6]:
import torch    #정수형 데이터 타입 코딩

In [7]:
a = torch.tensor(1, dtype = torch.uint8) #8비트 (부호없는)
print(a)

tensor(1, dtype=torch.uint8)


In [8]:
b = torch.tensor(-1, dtype = torch.int8)  #8비트 부호를 사용
print(b)

tensor(-1, dtype=torch.int8)


In [9]:
b = torch.tensor(-2, dtype = torch.uint8)
print(b)

tensor(254, dtype=torch.uint8)


In [10]:
c = torch.tensor(-1, dtype = torch.short) #16비트(16개의 이진자리스) 부호를 사용하여 (-32.768~32.767개)
print(c)

tensor(-1, dtype=torch.int16)


In [12]:
d = torch.tensor(-1, dtype = torch.int)
print(d)

tensor(-1, dtype=torch.int32)


In [13]:
e = torch.tensor(-1, dtype = torch.long)
print(e)
print(e.dtype)

tensor(-1)
torch.int64
