<a href="https://colab.research.google.com/github/jimmyjims88/computermath/blob/%EC%BD%94%EB%94%A9%EC%8B%A4%EC%8A%B5/4%EC%A3%BC%EC%B0%A8%20%EB%B2%A1%ED%84%B0%EC%9D%98%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch       #스칼라의 코드 표현-
#스칼라:크기만 있고 방향이 없는 물리량, 즉 방향성을 가지지 않는 성분이다.

#물리량에서의 스칼라 :물리량 중 시간, 부피, 질량, 온도, 속력, 에너지, 전위 등은 스칼라량이다.


In [3]:
a = torch.tensor(36.5)   #36.5 ->스칼라실수

print(a)

tensor(36.5000)


In [5]:
import torch #벡터 코딩
#벡터 :크기와 방향이 있는 물리량, 즉 크기에 방향성을 함께 고려하여야 설명이 가능한 물리량이다.

#물리량에서의 벡터 :물리량 중 변위, 속도, 가속도, 힘, 운동량, 충격량, 중력장, 전기장, 자기장 등은 벡터량이다.

In [6]:
b = torch.tensor([175, 60, 81, 0.8, 0.9])

print(b)

tensor([175.0000,  60.0000,  81.0000,   0.8000,   0.9000])


In [7]:
import torch  #벡터의 스칼라곱 코딩

In [8]:
c = torch.tensor(2)
d = torch.tensor([1, 2, 3, 4])

e = torch.mul(c, d)

print(e)

tensor([2, 4, 6, 8])


In [10]:
import torch #벡터의 합 코딩

In [11]:
f = torch.tensor([1, 2, 3, 4])
g = torch.tensor([1, 3, 5, 7])

h = torch.add(f, g)

print(h)

tensor([ 2,  5,  8, 11])


In [12]:
import torch #벡터의 차 코딩

In [14]:
i = torch.tensor([2, 4, 6, 8])
j = torch.tensor([2, 3, 4, 5])

k = torch.sub(i, j)

print(k)

tensor([0, 1, 2, 3])


In [15]:
import torch #벡터의 성분곱 코딩

In [17]:
l = torch.tensor([1, 2, 1, 3])
m = torch.tensor([2, 3, 1, 4])

n = torch.mul(l, m)

print(n)

tensor([ 2,  6,  1, 12])
